name : Unity guide
brand : InsightSquared
description : Unified design dev guide for InsightSquared
keyword: 
url : http://www.InsightSquared.com
imageurl: 
email : lwilliams@insightsquared.com
twitter : 
github : ell0ell0
author: Lee Williams
analytics: 
year: 2014
markdown: kramdown
